name: .NET Framework

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    
    #- name: Setup MSBuild
    #  uses: microsoft/setup-msbuild@v1
    
    #- name: Setup NuGet
    #  uses: NuGet/setup-nuget@v1.0.5
      
    #- name: setup-msbuild
    #  uses: microsoft/setup-msbuild@v1.1
    
    #- name: Restore Packages
    #  run: nuget restore test.sln
    
    #- name: Build solution
    #  run: msbuild RidgeDrawer.sln -t:rebuild -property:Configuration=Release
      
    - name: Build
      run: echo ${{ github.sha }} > Release.txt
    - name: Test
      run: cat Release.txt
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Release.txt
